---
- name: create snapshot
  become: true
  shell: "/usr/sbin/gluster snapshot create {{ item2.snapshot }} {{ item2.volume }} no-timestamp | awk '{ print $5}'"
  loop: "{{ item|flatten(levels=1) }}"
  loop_control:
    loop_var: item2

- name: activate snapshot
  become: true
  shell: "/usr/sbin/gluster snapshot activate {{ item2.snapshot }}"
  loop: "{{ item|flatten(levels=1) }}"
  loop_control:
    loop_var: item2