---
# Configure the prequisites for the bastion host
- name: Configure packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-client
    - atomic-openshift-clients
...