---
# Configure the prequisites for the bastion host
- name: Configure packages
  hosts: bastion[0]
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-client
    - heketi-client
    - atomic-openshift-clients
...