---
- name: create snapshot mountpoint
  become: true
  file:
    path: "{{ mount_directory }}/{{ item.snapshot }}"
    state: directory
  with_items: item

- name: Mount snapshot
  become: true
  mount:
    path: "{{ mount_directory }}/{{ item.snapshot }}"
    fstype: glusterfs
    src: "{{ groups['gluster'][0]['ansible_hostname'] }}:/snaps/{{ item.snapshot }}/{{ item.volume }}"
  with_items: item

- name: Create target directory
  become: true
  file:
    path: "/{{ snapshot_dir }}/{{ item.snapshot }}"
    state: directory
  with_items: item

- name: Tar the source
  archive:
    path:
      - "{{ mount_directory }}/{{ item.snapshot }}/*"
    dest: "{{ snapshot_dir }}/{{ item.snapshot }}.tar.bz2"
    format: bz2
  with_items: item

- name: unmount the snapshot volume
  become: true
  mount:
    path: "{{ mount_directory }}/{{ item.snapshot }}"
    state: unmounted 
  with_items: item