---

- name: Backup the old storageclass
  shell: oc get sc glusterfs-storage > /tmp/glusterfs-storage.yaml.tmp
  when: storageclass_overwrite_config|bool == true

- name: Remove the old storageclass
  shell: oc delete sc glusterfs-storage
  when: storageclass_overwrite_config|bool == true

- name: Put the new storage class on the server
  template:
    src: storageclass.yaml.j2
    dest: /tmp/storageclass.yaml.new
  when: storageclass_overwrite_config|bool == true